### ISSUE TITLE
CUDA 11.3 support

### ISSUE THREAD

**Issue by psychocoderHPC** [alpaka-group/alpaka#1293]
CUDA 11.3. is released and should be added.

There are some issues with CUDA 11.3

```
/alpaka/event/EventGenericThreads.hpp:280:19: error: ‘__T30’ was not declared in this scope
                 auto vQueues(dev.getAllQueues())
```

This can be solved by changing:

```C++
auto vQueues(dev.getAllQueues());
```
to
```C++
auto vQueues = dev.getAllQueues();
```

**Comment by psychocoderHPC** [comment]
I am currently work on adding CUDA 11.3 and fixing the issues.

**Comment by sbastrakov** [comment]
Do we need to backport it to 0.6.1? The 0.6.0 release didn't support CUDA 11.3.

**Comment by j-stephan** [comment]
0.6 is older than CUDA 11.3, so I'd say no. We are backporting specific features because of users who use older CUDA versions. I doubt they're planning to adopt CUDA 11.3 and stick with alpaka 0.6.x at the same time.

**Comment by psychocoderHPC** [comment]
> Do we need to backport it to 0.6.1? The 0.6.0 release didn't support CUDA 11.3.

Yes I would like to port it back. The reason is that we have already an issue in PIConGPU: https://github.com/ComputationalRadiationPhysics/picongpu/issues/3591 and I assume we will get soon more.

I assume that a backport is easy and should provide a low amount of conflicts.

Never the less we can discuss it tomorrow in the developer meeting.
