### ISSUE TITLE
Internal catch2 no longer compiles on gcc 11.2

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/alpaka#1460]
I just tried compiling with the internal Catch2 and got a compilation error. The bug was fixed upstream here: https://github.com/catchorg/Catch2/issues/2178

We should update the internal Catch2 of alpaka or just drop it entirely.
