### PR TITLE
fix clang9/nvcc11.2 boost bug

### PR DESCRIPTION
**Pull request by psychocoderHPC**
This PR fix current CI issues with clang + nvcc and disable workarounds for C++20 and newer.

```
/boost/boost/atomic/detail/bitwise_cast.hpp(113): error: type name is not allowed
```

- disable atomic_ref for clang<12&nvcc<11.6

The second commit fixes Windows compile issues those popped up today, maybe due to another MSVC update in the github workflow windows containers.

Issues introduced with #2288 where we enabled atomic ref after we introduced a bug that it was always disabled.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@fwyzard You observed already in #2288 issues with clang+nvcc and due to #2296 it shows that more combinations are affected.

File: include/alpaka/atomic/AtomicAtomicRef.hpp [hunk 1]
```diff
@@ -42,7 +42,7 @@ namespace alpaka
     void isSupportedByAtomicAtomicRef()
     {
         static_assert(
-            std::is_trivially_copyable_v<T> && detail::atomic_ref<T>::required_alignment <= alignof(T),
+            std::is_trivially_copyable_v<T> && alpaka::detail::atomic_ref<T>::required_alignment <= alignof(T),
```
Comment (fwyzard) [inline include/alpaka/atomic/AtomicAtomicRef.hpp:45]: Why do we need this ? We are already inside the `alpaka` namespace.

Comment (fwyzard) [reply include/alpaka/atomic/AtomicAtomicRef.hpp:45]: Ah, wait, this fixes the errors we have seen with clang 9 and cuda 11 ?

File: include/alpaka/atomic/AtomicCpu.hpp [hunk 2]
```diff
@@ -6,10 +6,11 @@
...
 #include "alpaka/core/BoostPredef.hpp"
 
-// clang 9 fails at compile time when using boost::atomic_ref
+// clang 9/10/11 together with nvcc<11.6.0 as host compiler fails at compile time when using boost::atomic_ref
 #ifdef BOOST_COMP_CLANG_AVAILABLE
-#    if BOOST_COMP_CLANG < BOOST_VERSION_NUMBER(11, 0, 0)
-#        ifndef ALPAKA_DISABLE_ATOMIC_ATOMICREF
+#    if(BOOST_COMP_CLANG < BOOST_VERSION_NUMBER(12, 0, 0) && BOOST_COMP_NVCC                                          \
+        && BOOST_COMP_NVCC < BOOST_VERSION_NUMBER(11, 6, 0))
+#        if !defined(ALPAKA_DISABLE_ATOMIC_ATOMICREF)
```
Comment (fwyzard) [inline include/alpaka/atomic/AtomicCpu.hpp:13]: do we still need this with the `alpaka::` change ?

**Comment by mehmetyusufoglu** [comment]
> This PR fix current CI issues with clang + nvcc and disable workarounds for C++20 and newer.
> 
> ```
> /boost/boost/atomic/detail/bitwise_cast.hpp(113): error: type name is not allowed
> ```
> 
>     * disable atomic_ref for clang<12&nvcc<11.6
> 
> 
> The second commit fixes Windows compile issues those popped up today, maybe due to another MSVC update in the github workflow windows containers.
> 
> Issues introduced with #2288 where we enabled atomic ref after we introduced a bug that it was always disabled.

@SimeonEhrig  Do you think we can prepare a setup for that compiler configuration, i tried on HAL but current options not available. Being not able to test easily is preventing when we have a problem with nvcc11.2 and clang9/10 etc.

File: include/alpaka/atomic/AtomicAtomicRef.hpp (hunk 1 above)
Comment (psychocoderHPC) [reply include/alpaka/atomic/AtomicAtomicRef.hpp:45]: This is fixing a windows bug that the lookup not works and the type is not found. It is similar to https://github.com/alpaka-group/alpaka/pull/2265.
The fix is in the second commit and this error show up yesterday, I assume the msvc version in the container is updated again and this is as new error :-(

File: include/alpaka/atomic/AtomicCpu.hpp (hunk 2 above)
Comment (psychocoderHPC) [reply include/alpaka/atomic/AtomicCpu.hpp:13]: yes, it is a new window bug :-(

**Comment by psychocoderHPC** [comment]
> > This PR fix current CI issues with clang + nvcc and disable workarounds for C++20 and newer.
> > ```
> > /boost/boost/atomic/detail/bitwise_cast.hpp(113): error: type name is not allowed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > * disable atomic_ref for clang<12&nvcc<11.6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The second commit fixes Windows compile issues those popped up today, maybe due to another MSVC update in the github workflow windows containers.
> > Issues introduced with #2288 where we enabled atomic ref after we introduced a bug that it was always disabled.
> 
> @SimeonEhrig Do you think we can prepare a setup for that compiler configuration, i tried on HAL but current options not available. Being not able to test easily is preventing when we have a problem with nvcc11.2 and clang9/10 etc.

Independent of this PR: In prinziple it is possible but you can always use the CI docker container to reproduce issues.

**Comment by mehmetyusufoglu** [comment]
> > > This PR fix current CI issues with clang + nvcc and disable workarounds for C++20 and newer.
> > > ```
> > > /boost/boost/atomic/detail/bitwise_cast.hpp(113): error: type name is not allowed
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > * disable atomic_ref for clang<12&nvcc<11.6
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The second commit fixes Windows compile issues those popped up today, maybe due to another MSVC update in the github workflow windows containers.
> > > Issues introduced with #2288 where we enabled atomic ref after we introduced a bug that it was always disabled.
> > 
> > 
> > @SimeonEhrig Do you think we can prepare a setup for that compiler configuration, i tried on HAL but current options not available. Being not able to test easily is preventing when we have a problem with nvcc11.2 and clang9/10 etc.
> 
> Independent of this PR: In prinziple it is possible but you can always use the CI docker container to reproduce issues.

ok, i will try in the evening. I will document it if possible so that people can do easily....

**Comment by mehmetyusufoglu** [comment]
> > > > This PR fix current CI issues with clang + nvcc and disable workarounds for C++20 and newer.
> > > > ```
> > > > /boost/boost/atomic/detail/bitwise_cast.hpp(113): error: type name is not allowed
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > * disable atomic_ref for clang<12&nvcc<11.6
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The second commit fixes Windows compile issues those popped up today, maybe due to another MSVC update in the github workflow windows containers.
> > > > Issues introduced with #2288 where we enabled atomic ref after we introduced a bug that it was always disabled.
> > > 
> > > 
> > > @SimeonEhrig Do you think we can prepare a setup for that compiler configuration, i tried on HAL but current options not available. Being not able to test easily is preventing when we have a problem with nvcc11.2 and clang9/10 etc.
> > 
> > 
> > Independent of this PR: In prinziple it is possible but you can always use the CI docker container to reproduce issues.
> 
> ok, i will try in the evening. I will document it if possible so that people can do easily....

Ok works, great. Thank you good for compile errors.

**Review by fwyzard — APPROVED** [review]
