### ISSUE TITLE
compile error at global mem alloc when RDC is false

### ISSUE THREAD

**Issue by mehmetyusufoglu** [alpaka-group/alpaka#2259]
I faced a compile error at Develop branch:

```
 alpaka/test/unit/mem/view/src/ViewStaticAccMem.cpp(19): error: An inline __device__/__constant__/__managed__ variable must have internal linkage when the program is compiled in whole program mode (-rdc=false)
                              alpaka::DevGlobal<TAcc, Elem[3][2]> g_globalMemory2DUninitialized;
```

- Error is observed when alpaka_RELOCATABLE_DEVICE_CODE cmake variable is DEFAULT or OFF. 
- Error is not observed when alpaka_RELOCATABLE_DEVICE_CODE cmake variable is ON.

**Comment by SimeonEhrig** [comment]
I checked the CI jobs again. There is a hand written job, which test RDC:
* https://github.com/alpaka-group/alpaka/blob/develop/script/gitlabci/job_cuda.yml
* current dev: https://gitlab.com/hzdr/crp/alpaka/-/jobs/6648385841

It tests nvcc 12.0 with gcc 12. Maybe your problem is a version specific bug. Which nvcc and host compiler version do you use?

**Comment by mehmetyusufoglu** [comment]
> I checked the CI jobs again. There is a hand written job, which test RDC:
> 
>     * https://github.com/alpaka-group/alpaka/blob/develop/script/gitlabci/job_cuda.yml
> 
>     * current dev: https://gitlab.com/hzdr/crp/alpaka/-/jobs/6648385841
> 
> 
> It tests nvcc 12.0 with gcc 12. Maybe your problem is a version specific bug. Which nvcc and host compiler version do you use?

Error disapperars when the flag is ON. The CI checks the ON version not when the flag is OFF ?  My config is nvcc 12.4 , gcc 12.3

**Comment by psychocoderHPC** [comment]
Maybe the problem is introduced in #2242 
Before the change, we always declared the variable `extern` too see: https://github.com/alpaka-group/alpaka/pull/2242/files#diff-2eddedd7c8abe84214af714d0e61060a85e1ef924b16bad0e7bb6fff54b250b8L25

@AuroraPerego Do you know why you removed the additional `extern` declaration of the variable?

**Comment by AuroraPerego** [comment]
> Do you know why you removed the additional `extern` declaration of the variable?

With the new implementation the `extern` declaration was not working, I used the `inline` attribute instead

**Comment by psychocoderHPC** [comment]
> > Do you know why you removed the additional `extern` declaration of the variable?
> 
> With the new implementation the `extern` declaration was not working, I used the `inline` attribute instead

Thanks for the fast response.

**Comment by psychocoderHPC** [comment]
https://reviews.llvm.org/D88786?id=295997 looks like a discussion about this topic for llvm behaviours

**Comment by AuroraPerego** [comment]
yes, we finished on the same page :)
I'll look into it tomorrow with Mehmet

**Comment by AuroraPerego** [comment]
I confirm that this is version-specific, I can reproduce it with CUDA 12.4 and the flag `-rdc=false` but not with CUDA 12.{0,1,2}.
It compiles with `static` instead of `inline` (see [PR #2242-comment](https://github.com/alpaka-group/alpaka/pull/2242#discussion_r1576532358)).

**Comment by psychocoderHPC** [comment]
fixed with https://github.com/alpaka-group/alpaka/pull/2303
